### ISSUE TITLE
Upgrade Error...

### ISSUE THREAD

**Issue by kevmullet100** [v1tal3/netconfig#62] opened 2018-02-21 15:28 UTC
Me again!
I've tried the upgrade again using the upgrade.sh.
It's showing as successful upgrade to 1.3.4a, but showing a spawn error

sudo supervisorctl start netconfig
netconfig: ERROR (spawn error)

When browsing to netconfig server I get an nginx error 502 bad gateway
nginx error log shows:

2018/02/21 15:05:17 [error] 15857#15857: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 10.95.130.77, server: netconfig.sanitised.uk, request: "GET /login HTTP/1.1", upstream: "http://127.0.0.1:8000/login", host: "10.95.130.80"
2018/02/21 15:05:17 [error] 15857#15857: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 10.95.130.77, server: netconfig.sanitised.uk, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8000/favicon.ico", host: "10.95.130.80", referrer: "https://10.95.130.80/login"

**Comment by matt852** [comment] 2018-02-21 15:37
Hi Kev, thanks for the bug reports!  I'll take a look at this tonight.  I'm sorry about these past couple issues, I thought I ironed them out for the upgrading.

Do you remember what version you were upgrading from?

**Comment by kevmullet100** [comment] 2018-02-21 15:55
No worries, there's a good possibility it is something local on my machine!
Think I was upgrading from 1.3.1

Cheers

**Comment by matt852** [comment] 2018-02-22 15:14
I'm trying to replicate the issue but am having a hard time doing so.  I assume you've tried rebooting already?  If not, can you?  It sounds like the gunicorn or nginx service may not be running correctly for some reason.

Also, can you try "sudo pip install requests" and then try restarting the services again, via "sudo supervisorctl restart netconfig"?  I ran into an issue with that in 1.3.4, and it should be fixed now in 1.3.4a.

Start with that, let me know how it works out.  I'll keep digging on my end.  Thanks.

**Comment by kevmullet100** [comment] 2018-02-23 11:03
Rebooted and done the below to no avail...

netconfig@UbuntuKev:~$ 
netconfig@UbuntuKev:~$ pip install requests
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests)
netconfig@UbuntuKev:~$ sudo supervisorctl restart netconfig
netconfig: ERROR (not running)
netconfig: ERROR (spawn error)
netconfig@UbuntuKev:~$ 


Not sure why there are strike outs

**Comment by matt852** [comment] 2018-02-23 14:56
Thanks Kev.  So I've rebuilt a fresh Ubuntu install from scratch, and installed NetConfig v1.3.2 on it.  we worked on a previous issue, where 1.3.2 fixed your issue, so I'm pretty sure that's what you were on.

I then ran the upgrade.sh script, and didn't encounter any errors.  I then rebuilt the server, installed v1.3.1 on it, upgraded to 1.3.2 (where we encountered the database bug from earlier, but fixed it for this), then ran the upgrade.sh script again to 1.3.4a.  I still can't reproduce it.

Let's get some debugs from the supervisorctl process, and I'll review them:
SSH into the server, and edit its config file:
`sudo vi /etc/supervisor/supervisord.conf`

In the section [supervisord], you'll see some settings for logfile, pidfile, etc.  We want to add a line in this section:
`loglevel=debug`

Now restart the supervisor process
`sudo service supervisor restart`

Then restart the NetConfig service
`sudo supervisorctl restart netconfig`

You should now have debug level logs in the /var/log/supervisor folder.  Copy the relevant output for the latest netconfig service restart attempt (or just the whole file, your choice), and attach them here.  You can also clear out the files prior to restarting the netconfig service, so you just get the relevant logs for the issue.

There should be 3 files:
netconfig-stderr---supervisor-[random].log
netconfig-stdout---supervisor-[random].log
supervisord.log

After this, feel free to remove the loglevel config setting in the supervisord.conf file and restarting its service again, to reset the logging level back to default.

**Comment by kevmullet100** [comment] 2018-02-28 11:09
Hi 
Thanks for this, and sorry for the delay. I'll rebuild the machine if this gets nowhere.
Outputs are below

Supervisord output
https://pastebin.com/8z3F26p4

netconfig-stderr
https://pastebin.com/Dd72xUJY

netconfig-stdout this is blank

**Comment by matt852** [comment] 2018-03-02 02:26
Hi Kev,

It looks like you're missing the pyopenssl module.  You can install it, or force it to upgrade if already installed, via the following:

`sudo pip install -U pyopenssl`

Do that, then try the command to restart the service again;

`sudo supervisorctl restart netconfig`

Tell me what happens.

**Comment by kevmullet100** [comment] 2018-03-02 08:55
Yep that has fixed it!
Not sure why that wasn't installed?

Thanks

**Comment by matt852** [comment] 2018-03-02 17:19
I'm not sure, but I'll add it to the requirements list in the next update, to make sure it is installed.

For future troubleshooting, here's how I found the issue:

After Kev set the logging to debug, his netconfig-stderr file contained the following errors:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/dist-packages/gunicorn/util.py", line 366, in import_app
    __import__(module)
  File "/home/netconfig/netconfig/app/__init__.py", line 6, in <module>
    from scripts_bank.netboxAPI import NetboxHost
  File "/home/netconfig/netconfig/app/scripts_bank/netboxAPI.py", line 1, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
[2018-02-28 10:50:05 +0000] [9376] [INFO] Worker exiting (pid: 9376)
[2018-02-28 10:50:05 +0000] [9371] [INFO] Shutting down: Master
[2018-02-28 10:50:05 +0000] [9371] [INFO] Reason: Worker failed to boot.
```


This shows that the process attempted to start but failed due to a missing package.  The key lines to look at are near the end:

```
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
```

Looking up the Python/pip installable package name for OpenSSL showed it as 'pyopenssl'.  Once it was installed, the 'module' object having no attribute in 'SSL_ST_INIT' now exists.

**Closed as completed** 2018-03-05 17:30 UTC
Labels: fixed
